# Generated by Django 6.0.1 on 2026-02-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='is_done',
        ),
    ]
